Entrega2: Entrega2.o functions.o functions.h
	g++ -Wall -g Entrega2.o functions.o -o Entrega2

Entrega2.o: Entrega2.cpp
	g++ -Wall -c Entrega2.cpp

functions.o: functions.cpp functions.h
	g++ -Wall -c functions.cpp

clean:
	rm *.o Entrega2 solucionInicial.txt