Ent2: Ent2.o functions.o functions.h
	g++ -Wall -g Ent2.o functions.o -o Ent2

Ent2.o: Ent2.cpp
	g++ -Wall -c Ent2.cpp

functions.o: functions.cpp functions.h
	g++ -Wall -c functions.cpp

clean:
	rm *.o Ent2 solucionInicial.txt